AsteroidOS/qml-asteroid

src/controls/qml/Switch.qml

The current state of the Switch component feels not consistent with the rest of AsteroidOS. This PR attempts to change that.
Another thing that this adds is a disabled/not available state.
See the comparison below for before and after. Feedback is, as always, welcome :wink: 
Before   | After | Disabled 
:------------------------:|:-------------------------:|:-------------------------:
Alarm clock  (enabled)   | Alarm clock (disabled) |
:------------------------:|:-------------------------:

Switch: Change style to be more consistent with overall.

---

src/controls/qml/Dims.qml

Dims.dp is not defined in the code. Dims.h is and "... of screen height" + "Dims::h when you need a dimension relative to the height." implies that dp is outdated or a typo.

replaces Dims.dp with Dims.h in documentation

---

src/utils/src/deviceinfo.cpp
src/utils/src/deviceinfo.h

Move away from using compile time watch specifics. Use a configuration file `machine.conf` if it is provided by a `meta-*-hybris` layer.
Main benefits:
- Won't have to compile `qml-asteroid` for every watch.
- Allows for configuration changes that aren't recommended (i.e. disable burn-in-protection on OLED displays).
I have created a `machine.conf` for `sturgeon` (https://github.com/AsteroidOS/meta-sturgeon-hybris/pull/13). Depending on changes required I will also adjust the other `hybris` layers when no more changes are required.

DeviceInfo: Use config file for device specific settings.

---

src/utils/CMakeLists.txt
src/utils/src/fileinfo.cpp
src/utils/src/fileinfo.h

Provides a simple mechanism to check if a file exists or not.
This is part of the work done by @eLtMosen. (https://github.com/AsteroidOS/asteroid-settings/pull/39)
Prior to merging, I still would like to add support for file name patterns: `file://` and `qrc://`. Which basically is just replacing those with the pattern that `QFile` expects.

Adds FileInfo.

---

src/controls/src/flatmesh.cpp
src/controls/src/flatmesh.h

There's no point in updating the flatmesh when the animation has been disabled.
Additionally, disable the animation when the flatmesh isn't enabled.
This works nicely in conjunction with https://github.com/AsteroidOS/asteroid-launcher/pull/87.
It seems to reduce power usage when the FlatMesh is used as the wallpaper.

FlatMesh: Disable animation timer when invisible.

---

src/controls/qml/StatusPage.qml

This adjusts the left and right margin so that it looks better on round watches.
This is a comparision of the previous and new look on round displays.
| Old | New |
|------|--------|
| ![nar-old-mar](https://user-images.githubusercontent.com/7857908/178146405-36d1891a-a183-460f-b170-9cb0ff368d03.jpg) | ![nar-mar](https://user-images.githubusercontent.com/7857908/178146401-a2b26ea5-b344-490e-8637-b85fe2c475cd.jpg) |
Here's a comparison on a rectangular display.
| Old | New |
|------|--------|
| ![bel_c1](https://user-images.githubusercontent.com/7857908/178146297-3b66b547-6bca-4caa-bc12-22a7efbf1d81.jpg) | ![bel_c2](https://user-images.githubusercontent.com/7857908/178146301-a3836166-6ca6-4510-8607-268f9d92fc18.jpg) |

StatusPage: Adjust text margins to fit better on the screen.

---

src/controls/qml/LayerStack.qml

The behaviour previously was that 'firstpage' was loaded in once when the item was initialised, and was then ignored. While this makes sense on some level, it severely complicates the development of more complex UIs. It also does not align with other Qt modules, where most properties will update live. This change makes the layerstack update when firstpage property is changed. 
Example:
An application needs the user to log in on the first run. If the dialog is pushed to the layerstack, then it can be dismissed by the user, which will lead to them seeing a UI that is not yet intended to be seen.
an alternative solution for this kind of issue would be to load in a much larger firstpage, which has invisible components that only become visible for the first run - however, these components will …

Layerstack respects changing 'firstpage'

---

src/controls/qml/LabeledSwitch.qml
src/controls/qmldir
src/controls/resources.qrc

This adds a LabeledSwitch control to simplify and standardize many of the settings pages.  It has four properties:
multiplier - a real representing the portion of the width used for the
label to the left of the switch (default 0.7143 to match existing ratios)
fontratio - a real representing the ratio of font size to height
(default: 0.3 to match existing ratios)
checked - a bool
text - a string for the label to the left of the switch
Signed-off-by: Ed Beroset <beroset@ieee.org>

Add a LabeledSwitch control

---

src/controls/qml/IntSelector.qml
src/controls/qmldir
src/controls/resources.qrc

The PercentControl object is intended to be used for percentage settings, such as brightness or volume, but is written in a way that is intended to be generally useful.  It derives from the recent version of IconButton and has the following settable properties:
min - an integer describing the minimum value (default: 0) max - an integer describing the maximum value (default: 100) stepsize - an integer step size (default: 10)
marker - a string appended to the value display (default: "%") value - an integer representing the initial value (default: 0) multiplier - a real representing the portion of the width used for the label between the two icons (default 0.42857 to match existing ratios) fontratio - a real representing the ratio of font size to height (default: 0.3 to match existing …

Add PercentControl object

---

src/controls/qml/IntSelector.qml
src/controls/qml/LabeledSwitch.qml

QML extension components seem to generally use absolute pixel values (in our case, the equivalent being dims) as default values. The way these are currently set up causes them to behave inconsistently in columns and rows, requiring workarounds to get them to work correctly. This commit brings them in line with other controls in qml-asteroid.

Use dims as default size for intselector and labeledswitch controls

---

src/controls/qml/Application.qml

the left and right indicators previously appeared at the window center, which does not align with the visual center of the display. This moves them down by half the flat tyre height to compensate.
This only fixes the indicators in the window element. This does not affect all indicators everywhere.
After thinking about the flat tyre problem for a very long time, I came to the conclusion that it should be compensated for on a case-by-case basis. Developers already have access to the raw flat tyre height, so small changes like these will be needed everywhere to make this work.

Center indicators in window on flat tyre watches

---

CMakeLists.txt
README.md
src/CMakeLists.txt
src/utils/src/deviceinfo.cpp

This adds support for building, installing and running org.asteroid.controls and org.asteroid.utils on a desktop development machine, allowing for easier development and testing of watchfaces on a desktop Linux machine.  This fixes https://github.com/AsteroidOS/unofficial-watchfaces/issues/37

Create desktop modules

---

CMakeLists.txt
src/controls/doc/asteroid_controls.qdocconf

This adds a "doc" target for the CMake file so that HTML documentation for the controls is built in "doc/html".

Add doc target for build

---

src/controls/qml/LayerStack.qml

This fixes a non-fatal error introduced by me in ed6d164f897c57d24520580c78b5a4f6d409ce04 that caused significant log spam.
Errors would show up like this:
```
TypeError: Cannot call method 'destroy' of undefined
```
This would happen because the code tried to destroy the firstPage before it had even been created. A simple check of whether firstPageItem exists is all that was needed here. 
This also copies the safety check to onFirstPageChanged, and removes component.onCompleted, since the two functions are redundant and are both called in the creation process.

Fix layerstack destroy error

---

src/controls/qml/PageHeader.qml

- Add gradient from near black to transparent behind the title Label to mitigate clipping with of scrolling page content
- Change Fonttype to SemiCondensed Light, to be consistent with the Settings main ListItem
- Add wrapper Item around the rectangle and Label. This makes it necessary to forward the alias for text to the Label.text since some calls of the component assume it is a Label and push the title to the Label.text property.
This requires changes to all pages and apps where PageHeader is used. The PageHeader call needs to be moved last in code order to prevent the text content to scroll on top of the PageHeader. Implementation of this change into the settings pages here https://github.com/AsteroidOS/asteroid-settings/pull/84
Signed-off-by: Timo Könnecke koennecke@mosushi.de …

Redesign PageHeader component

---

src/controls/qml/HighlightBar.qml
src/controls/qml/IntSelector.qml
src/controls/qml/LabeledActionButton.qml
src/controls/qml/LabeledSwitch.qml
src/controls/qml/ListItem.qml
src/controls/qmldir
src/controls/resources.qrc

Unifiy the layouts of the components used on the settings pages to fixed font and icon size.
Give horizontal spacing/margin within the component so the full width of the screen can be used and must not be limited by margins given in the settings pages.
- Move ListItem from asteroid-settings
- Add LabeledActionButton analog to LabeledSwitch
- Add HighlightBar used in LabeledSwitch
- Refactor LabeledSwitch to fixed Dims.h(20) icon height and Dims.h(25) rowHeight
- Refactor IntSelector to fixed Dims.h(20) icon height and Dims.h(25) rowHeight
- Update qmldir and resource.qrc with new components

Unify settings pages components

---

src/app/asteroidapp.cpp

Removes the extension from the filename used to load the application translations.
This is required as otherwise https://github.com/AsteroidOS/asteroid-alarmclock/pull/20 will not work as it tries to load translations with the name `asteroid-flashlight.so.en_GB.qm` instead of `asteroid-flashlight.en_GB.qm`.

AsteroidApp: Remove extension from filename.

---

src/controls/qml/IntSelector.qml

The recent refactoring removed the former labelWidthRatio property, but the code was still referring to it to set the width of the label in the middle of the IntSelector control.  This fix simply removes the explict width setting because it is implied by the anchors and the widths of the left and right buttons.

Remove width from IntSelector label

---

src/controls/qml/IconButton.qml

This should allow all other signals of MouseArea to be easily used by developers and puts IconButton in line with the behaviour of QtQuick Controls Button.
To my understanding, this shouldn't break any existing apps, but I haven't had a chance to test with all apps yet.

Change IconButton to inherit MouseArea

---

src/controls/qml/CircularSpinner.qml
src/controls/qml/Dims.qml
src/controls/qml/IconButton.qml
src/controls/qml/IntSelector.qml
src/controls/qml/Label.qml
src/controls/qml/LabeledActionButton.qml
src/controls/qml/LabeledSwitch.qml
src/controls/qml/LayerStack.qml
src/controls/qml/Marquee.qml
src/controls/qml/PageDot.qml
src/controls/qml/PageHeader.qml
src/controls/qml/Spinner.qml
src/controls/qml/StatusPage.qml
src/controls/qml/Switch.qml

There was an error in several of the control documentation headers that had org.controls.asteroid instead of org.asteroid.controls.  This only affected the documentation and not how the controls actually work, which is why it hadn't been discovered until now.

Fix documentation of control classes

---

src/controls/qml/Application.qml
src/controls/qml/BorderGestureArea.qml
src/controls/qml/Dims.qml
src/controls/qml/ListItem.qml
src/controls/qml/PageHeader.qml
src/utils/CMakeLists.txt
src/utils/src/devicespecs.cpp
src/utils/src/devicespecs.h
src/utils/src/utils_plugin.cpp

This renames the DeviceInfo QML class in org.asteroid.utils to DeviceSpecs to avoid a conflict with an unrelated DeviceInfo class defined in org.nemomobile.systemsettings.
This fixes https://github.com/AsteroidOS/qml-asteroid/issues/56

Rename DeviceInfo to DeviceSpecs to remove conflict
